"""The image build pipeline.

Assembles a build context on disk, invokes BuildKit, streams the log, and
records the result — once per tier, base first.

Two structural choices differ from the prior art:

* The build context and the log directory are separate. SWE-bench writes its
  build log *into* the context directory and ships it to the daemon on every
  rebuild, and has no ``.dockerignore`` anywhere.
* A build is skipped when an image carrying the expected digest already exists.
  Because the digest covers the rendered Dockerfile, every context file and the
  parent reference, that check is sufficient on its own — there is no mtime
  comparison (Teich) and no manual force-rebuild flag to remember (SWE-bench).
"""

from __future__ import annotations

import shutil
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path

from jormungandr.runtime.compose import (
    BASE_TIER,
    RUNTIME_TIER,
    WORKSPACE_TIER,
    ComposedImage,
    ComposedLayer,
    compose,
)
from jormungandr.runtime.identity import LABEL_NAMESPACE
from jormungandr.runtime.docker import DockerCli, DockerError
from jormungandr.runtime.spec import ImageSpec

__all__ = ["BuildError", "BuildResult", "ImageBuilder", "LayerResult"]

MANAGED_LABEL = f"{LABEL_NAMESPACE}.managed"
DIGEST_LABEL = f"{LABEL_NAMESPACE}.digest"


def _dockerignore(context_files: Sequence[str]) -> str:
    """Deny everything, then allow exactly the declared files.

    The allow-list must be generated from the module-declared files: a static
    `*` + `!Dockerfile` silently drops every script a module asked to bake in,
    and the failure surfaces much later as a COPY that cannot find its source.
    """
    lines = [
        "# Generated by jormungandr.",
        "# The context holds exactly the files modules asked for; nothing else",
        "# should ever reach the daemon.",
        "*",
        "!Dockerfile",
        "!.dockerignore",
    ]
    lines += [f"!{name}" for name in sorted(context_files)]
    return "\n".join(lines) + "\n"


class BuildError(RuntimeError):
    """A build failed. Carries the path to its own log.

    An exception without the log path is unactionable when builds run in
    parallel — a lesson taken directly from SWE-bench's BuildImageError.
    """

    def __init__(self, reference: str, log_path: Path, detail: str) -> None:
        self.reference = reference
        self.log_path = log_path
        self.detail = detail
        super().__init__(f"failed to build {reference}: {detail}\nbuild log: {log_path}")


@dataclass(frozen=True, slots=True)
class LayerResult:
    tier: str
    reference: str
    digest: str
    image_id: str
    cached: bool
    log_path: Path
    context_dir: Path


@dataclass(frozen=True, slots=True)
class BuildResult:
    """Outcome of building every tier of one image."""

    layers: tuple[LayerResult, ...]

    @property
    def final(self) -> LayerResult:
        return self.layers[-1]

    @property
    def reference(self) -> str:
        return self.final.reference

    @property
    def digest(self) -> str:
        return self.final.digest

    @property
    def image_id(self) -> str:
        return self.final.image_id

    @property
    def cached(self) -> bool:
        """True only when every tier was already present."""
        return all(layer.cached for layer in self.layers)

    @property
    def built(self) -> bool:
        return not self.cached


class ImageBuilder:
    """Builds :class:`ImageSpec` recipes into images."""

    def __init__(
        self,
        *,
        state_dir: Path | None = None,
        docker: DockerCli | None = None,
    ) -> None:
        self.state_dir = Path(
            state_dir if state_dir is not None else Path.home() / ".cache" / "jormungandr"
        ).expanduser()
        self.docker = docker or DockerCli()

    # -- paths ------------------------------------------------------------

    def context_dir(self, digest: str) -> Path:
        return self.state_dir / "build" / digest / "context"

    def log_path(self, digest: str) -> Path:
        return self.state_dir / "build" / digest / "build.log"

    # -- context ----------------------------------------------------------

    def write_context(self, layer: ComposedLayer) -> Path:
        """Materialize a tier's build context.

        Rewritten from scratch each time so a stale file from a previous
        composition can never linger in the context.
        """
        context = self.context_dir(layer.digest)
        if context.exists():
            shutil.rmtree(context)
        context.mkdir(parents=True, exist_ok=True)

        (context / "Dockerfile").write_text(layer.dockerfile, encoding="utf-8")
        (context / ".dockerignore").write_text(
            _dockerignore(list(layer.context_files)), encoding="utf-8"
        )
        for name, content in layer.context_files.items():
            target = context / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            target.chmod(layer.context_modes.get(name, 0o644))
        return context

    # -- build ------------------------------------------------------------

    def build(
        self,
        spec: ImageSpec,
        *,
        force: bool = False,
        on_output: Callable[[str], None] | None = None,
        extra_args: Sequence[str] = (),
    ) -> BuildResult:
        """Build every tier of ``spec``, skipping those that already exist."""
        return self.build_composed(
            compose(spec), force=force, on_output=on_output, extra_args=extra_args
        )

    def build_layer(
        self,
        layer: ComposedLayer,
        *,
        platform: str,
        force: bool = False,
        on_output: Callable[[str], None] | None = None,
    ) -> LayerResult:
        """Build a single tier that was composed outside an ImageSpec."""
        self.docker.require()
        return self._build_layer(
            layer,
            platform=platform,
            build_args={},
            force=force,
            on_output=on_output,
            extra_args=(),
        )

    def build_composed(
        self,
        composed: ComposedImage,
        *,
        force: bool = False,
        on_output: Callable[[str], None] | None = None,
        extra_args: Sequence[str] = (),
    ) -> BuildResult:
        self.docker.require()
        results: list[LayerResult] = []
        for layer in composed.layers:
            results.append(
                self._build_layer(
                    layer,
                    platform=composed.spec.target_platform,
                    build_args=composed.spec.build_args,
                    force=force,
                    on_output=on_output,
                    extra_args=extra_args,
                )
            )
        return BuildResult(layers=tuple(results))

    def _build_layer(
        self,
        layer: ComposedLayer,
        *,
        platform: str,
        build_args: dict[str, str],
        force: bool,
        on_output: Callable[[str], None] | None,
        extra_args: Sequence[str],
    ) -> LayerResult:
        log_path = self.log_path(layer.digest)
        log_path.parent.mkdir(parents=True, exist_ok=True)

        if not force and self.docker.image_exists(layer.reference):
            return LayerResult(
                tier=layer.tier,
                reference=layer.reference,
                digest=layer.digest,
                image_id=self.docker.image_digest(layer.reference),
                cached=True,
                log_path=log_path,
                context_dir=self.context_dir(layer.digest),
            )

        context = self.write_context(layer)
        args = [
            "build",
            "--platform",
            platform,
            "--tag",
            layer.reference,
            "--progress",
            "plain",
        ]
        if force:
            args.append("--no-cache")
        for key, value in sorted(build_args.items()):
            args += ["--build-arg", f"{key}={value}"]
        args.extend(extra_args)
        args.append(str(context))

        with log_path.open("w", encoding="utf-8") as log:
            log.write(f"$ docker {' '.join(args)}\n\n")
            # Echo the generated Dockerfile before running it: when a build
            # fails, the exact input is the first thing anyone needs.
            log.write(layer.dockerfile)
            log.write("\n" + "-" * 70 + "\n")
            log.flush()
            try:
                for line in self.docker.stream(args):
                    log.write(line + "\n")
                    if on_output is not None:
                        on_output(line)
            except DockerError as exc:
                log.write(f"\nBUILD FAILED: {exc}\n")
                raise BuildError(layer.reference, log_path, str(exc)) from exc

        return LayerResult(
            tier=layer.tier,
            reference=layer.reference,
            digest=layer.digest,
            image_id=self.docker.image_digest(layer.reference),
            cached=False,
            log_path=log_path,
            context_dir=context,
        )

    # -- housekeeping -----------------------------------------------------

    def managed_images(self) -> list[dict[str, str]]:
        """Images this tool actually built.

        The label alone is not sufficient. Docker propagates a parent image's
        LABELs into any child, so a user image built ``FROM`` one of ours also
        carries ``dev.jormungandr.managed=true`` and would be collected — an
        irreversible force-delete of something we did not create.

        The discriminator is that we embed the digest in the tag as well as in
        a label. A derived image inherits the *parent's* digest label, which
        cannot match the digest in its own tag, so requiring the two to agree
        keeps exactly the images this tool produced.
        """
        ours: list[dict[str, str]] = []
        for image in self.docker.list_images(label=f"{MANAGED_LABEL}=true"):
            tag = str(image.get("Tag", ""))
            digest = self.docker.image_label(
                f"{image.get('Repository')}:{tag}", DIGEST_LABEL
            )
            if digest and tag.endswith(digest):
                ours.append(image)
        return ours

    def prune(self, *, keep: Sequence[str] = ()) -> list[str]:
        """Remove managed images except those in ``keep``.

        Only ever touches images this tool built — see :meth:`managed_images`,
        which requires more than the label because Docker propagates labels
        into derived images.

        Removed newest-tier first: a tier cannot be deleted while another is
        built on it, and there are three of them, so distinguishing only
        "base or not" would leave runtime and workspace in arbitrary order and
        fail whenever runtime came first.
        """
        preserved = set(keep)
        removed: list[str] = []
        images = self.managed_images()

        # Deepest dependant first. An unrecognised tag sorts with the leaves,
        # so an unknown future tier is removed before what it might build on.
        depth = {f"{BASE_TIER}-": 0, f"{RUNTIME_TIER}-": 1, f"{WORKSPACE_TIER}-": 2}

        def tier_of(image: dict[str, str]) -> int:
            tag = str(image.get("Tag", ""))
            for prefix, rank in depth.items():
                if tag.startswith(prefix):
                    return rank
            return max(depth.values())

        for image in sorted(images, key=tier_of, reverse=True):
            reference = f"{image.get('Repository')}:{image.get('Tag')}"
            if reference in preserved:
                continue
            if self.docker.remove_image(reference, force=True):
                removed.append(reference)
        return removed
