"""The image build pipeline.

Assembles a build context on disk, invokes BuildKit, streams the log, and
records the result.

Two structural choices differ from the prior art:

* The build context and the log directory are separate. SWE-bench writes its
  build log *into* the context directory and ships it to the daemon on every
  rebuild, and has no ``.dockerignore`` anywhere.
* A build is skipped when an image carrying the expected digest already exists.
  Because the digest covers the rendered Dockerfile and every context file,
  that check is sufficient on its own — there is no mtime comparison (Teich)
  and no manual force-rebuild flag to remember (SWE-bench).
"""

from __future__ import annotations

import shutil
from collections.abc import Callable, Iterator, Sequence
from dataclasses import dataclass
from pathlib import Path

from jormungandr.runtime.compose import ComposedImage, compose
from jormungandr.runtime.docker import DockerCli, DockerError
from jormungandr.runtime.spec import ImageSpec

__all__ = ["BuildError", "BuildResult", "ImageBuilder"]

def _dockerignore(context_files: Sequence[str]) -> str:
    """Deny everything, then allow exactly the declared files.

    The allow-list must be generated from the module-declared files: a static
    `*` + `!Dockerfile` silently drops every script a module asked to bake in,
    and the failure surfaces much later as a COPY that cannot find its source.
    """
    lines = [
        "# Generated by jormungandr.",
        "# The context holds exactly the files modules asked for; nothing else",
        "# should ever reach the daemon.",
        "*",
        "!Dockerfile",
        "!.dockerignore",
    ]
    lines += [f"!{name}" for name in sorted(context_files)]
    return "\n".join(lines) + "\n"


class BuildError(RuntimeError):
    """A build failed. Carries the path to its own log.

    An exception without the log path is unactionable when builds run in
    parallel — a lesson taken directly from SWE-bench's BuildImageError.
    """

    def __init__(self, reference: str, log_path: Path, detail: str) -> None:
        self.reference = reference
        self.log_path = log_path
        self.detail = detail
        super().__init__(f"failed to build {reference}: {detail}\nbuild log: {log_path}")


@dataclass(frozen=True, slots=True)
class BuildResult:
    reference: str
    digest: str
    image_id: str
    cached: bool
    log_path: Path
    context_dir: Path

    @property
    def built(self) -> bool:
        return not self.cached


class ImageBuilder:
    """Builds :class:`ImageSpec` recipes into images."""

    def __init__(
        self,
        *,
        state_dir: Path | None = None,
        docker: DockerCli | None = None,
    ) -> None:
        self.state_dir = Path(
            state_dir if state_dir is not None else Path.home() / ".cache" / "jormungandr"
        ).expanduser()
        self.docker = docker or DockerCli()

    # -- paths ------------------------------------------------------------

    def context_dir(self, digest: str) -> Path:
        return self.state_dir / "build" / digest / "context"

    def log_path(self, digest: str) -> Path:
        return self.state_dir / "build" / digest / "build.log"

    # -- context ----------------------------------------------------------

    def write_context(self, composed: ComposedImage) -> Path:
        """Materialize the build context.

        Rewritten from scratch each time so a stale file from a previous
        composition can never linger in the context.
        """
        context = self.context_dir(composed.digest)
        if context.exists():
            shutil.rmtree(context)
        context.mkdir(parents=True, exist_ok=True)

        (context / "Dockerfile").write_text(composed.dockerfile, encoding="utf-8")
        (context / ".dockerignore").write_text(
            _dockerignore(list(composed.context_files)), encoding="utf-8"
        )

        declared = set(composed.context_files)
        for name, content in composed.context_files.items():
            target = context / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            target.chmod(composed.context_modes.get(name, 0o644))

        # Every declared file must actually be referenced by the Dockerfile.
        # SWE-bench only logs a warning here, which has been firing unnoticed
        # for six of its languages — a file silently never copied in.
        unused = {name for name in declared if name not in composed.dockerfile}
        if unused:
            raise BuildError(
                composed.reference,
                self.log_path(composed.digest),
                f"context files never referenced by the Dockerfile: {sorted(unused)}",
            )
        return context

    # -- build ------------------------------------------------------------

    def build(
        self,
        spec: ImageSpec,
        *,
        force: bool = False,
        on_output: Callable[[str], None] | None = None,
        extra_args: Sequence[str] = (),
    ) -> BuildResult:
        """Build the image described by ``spec``, or skip if it already exists."""
        composed = compose(spec)
        return self.build_composed(
            composed, force=force, on_output=on_output, extra_args=extra_args
        )

    def build_composed(
        self,
        composed: ComposedImage,
        *,
        force: bool = False,
        on_output: Callable[[str], None] | None = None,
        extra_args: Sequence[str] = (),
    ) -> BuildResult:
        self.docker.require()
        digest = composed.digest
        log_path = self.log_path(digest)
        log_path.parent.mkdir(parents=True, exist_ok=True)

        if not force and self.docker.image_exists(composed.reference):
            return BuildResult(
                reference=composed.reference,
                digest=digest,
                image_id=self.docker.image_digest(composed.reference),
                cached=True,
                log_path=log_path,
                context_dir=self.context_dir(digest),
            )

        context = self.write_context(composed)
        args = [
            "build",
            "--platform",
            composed.spec.target_platform,
            "--tag",
            composed.reference,
            "--progress",
            "plain",
        ]
        if force:
            args.append("--no-cache")
        for key, value in sorted(composed.spec.build_args.items()):
            args += ["--build-arg", f"{key}={value}"]
        args.extend(extra_args)
        args.append(str(context))

        with log_path.open("w", encoding="utf-8") as log:
            log.write(f"$ docker {' '.join(args)}\n\n")
            # Echo the generated Dockerfile before running it: when a build
            # fails, the exact input is the first thing anyone needs.
            log.write(composed.dockerfile)
            log.write("\n" + "-" * 70 + "\n")
            log.flush()
            try:
                for line in self.docker.stream(args):
                    log.write(line + "\n")
                    if on_output is not None:
                        on_output(line)
            except DockerError as exc:
                log.write(f"\nBUILD FAILED: {exc}\n")
                raise BuildError(composed.reference, log_path, str(exc)) from exc

        return BuildResult(
            reference=composed.reference,
            digest=digest,
            image_id=self.docker.image_digest(composed.reference),
            cached=False,
            log_path=log_path,
            context_dir=context,
        )

    # -- housekeeping -----------------------------------------------------

    def managed_images(self) -> list[dict[str, str]]:
        """Images this tool created, found by label rather than name prefix."""
        return self.docker.list_images(label="dev.jormungandr.managed=true")

    def prune(self, *, keep: Sequence[str] = ()) -> list[str]:
        """Remove managed images except those in ``keep``.

        Only ever touches images carrying our label, so a user's unrelated
        images cannot be collected. SWE-bench classifies by name prefix and
        will happily delete anything that happens to share it.
        """
        preserved = set(keep)
        removed: list[str] = []
        for image in self.managed_images():
            reference = f"{image.get('Repository')}:{image.get('Tag')}"
            if reference in preserved:
                continue
            if self.docker.remove_image(reference, force=True):
                removed.append(reference)
        return removed
