"""Turn an :class:`ImageSpec` into rendered Dockerfiles and build contexts.

Pure: no daemon, no network, no filesystem, no clock. That is what lets the
whole composition and identity layer be tested without Docker, and it is why
the resulting digests are trustworthy as cache keys.

An image is composed as two tiers:

* **base** — OS packages and language toolchains. Changes rarely, shared by
  every runtime image built on it.
* **runtime** — harnesses, integrations, user scripts. Changes often.

Each tier is independently content-addressed and independently tagged, so a
harness bump rebuilds only the runtime image, and a cold machine can pull the
base rather than rebuild it. The runtime's ``FROM`` names the base by its
content-addressed tag, so a base change propagates into the runtime digest
automatically — there is no separate bookkeeping to forget.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass

from jormungandr.runtime.identity import content_digest, image_labels, image_reference
from jormungandr.runtime.layers import (
    Arg,
    Comment,
    Copy,
    From,
    Instruction,
    Label,
    Run,
    User,
    Workdir,
    render_dockerfile,
)
from jormungandr.runtime.modules.base import BuildContext, Module
from jormungandr.runtime.modules.registry import ModuleRegistry, build_modules
from jormungandr.runtime.spec import ImageSpec

__all__ = [
    "BASE_TIER",
    "RUNTIME_TIER",
    "WORKSPACE_TIER",
    "compose_workspace",
    "ComposeError",
    "ComposedImage",
    "ComposedLayer",
    "compose",
]

BASE_TIER = "base"
RUNTIME_TIER = "runtime"
WORKSPACE_TIER = "workspace"


class ComposeError(ValueError):
    """A spec cannot be turned into a coherent image."""


@dataclass(frozen=True, slots=True)
class ComposedLayer:
    """One fully determined, not-yet-built tier."""

    tier: str
    dockerfile: str
    context_files: Mapping[str, str]
    context_modes: Mapping[str, int]
    digest: str
    reference: str
    module_names: tuple[str, ...]
    parent: str | None

    @property
    def tag(self) -> str:
        return self.reference.rsplit(":", 1)[1]


@dataclass(frozen=True, slots=True)
class ComposedImage:
    """The tiers of one image, base first."""

    spec: ImageSpec
    layers: tuple[ComposedLayer, ...]

    @property
    def base(self) -> ComposedLayer:
        return self.layers[0]

    @property
    def runtime(self) -> ComposedLayer:
        return self.layers[-1]

    # The image a caller ultimately runs is the last tier.
    @property
    def digest(self) -> str:
        return self.runtime.digest

    @property
    def reference(self) -> str:
        return self.runtime.reference

    @property
    def tag(self) -> str:
        return self.runtime.tag

    @property
    def dockerfile(self) -> str:
        return self.runtime.dockerfile

    @property
    def module_names(self) -> tuple[str, ...]:
        return tuple(n for layer in self.layers for n in layer.module_names)


def _check_context_files_are_used(
    files: Mapping[str, str],
    instructions: Sequence[Instruction],
    label: str,
) -> None:
    """Every file a module bakes into the context must actually be COPYed.

    Matched against the exact source list of each COPY instruction rather than
    by substring search over the Dockerfile text. A substring test both misses
    real mistakes — 'requirements.txt' is a substring of an unrelated
    '/opt/requirements.txt' mentioned in a RUN — and rejects a legitimate
    'COPY *.sh /opt/'.
    """
    if not files:
        return
    copied: set[str] = set()
    for instruction in instructions:
        if isinstance(instruction, Copy):
            copied.update(instruction.sources)

    unused = {
        name
        for name in files
        if name not in copied
        and not any(_matches_glob(name, source) for source in copied)
    }
    if unused:
        raise ComposeError(
            f"{label}: modules added context files that no COPY "
            f"instruction references: {sorted(unused)}"
        )


def _matches_glob(name: str, pattern: str) -> bool:
    from fnmatch import fnmatch

    return ("*" in pattern or "?" in pattern or "[" in pattern) and fnmatch(
        name, pattern
    )


def _compose_layer(
    *,
    spec: ImageSpec,
    tier: str,
    parent: str,
    modules: Sequence[Module],
    include_build_args: bool,
) -> ComposedLayer:
    context = BuildContext()
    body: list[Instruction] = [
        Comment(
            f"Generated by jormungandr ({tier} tier). Do not edit.\n"
            "Reproducible: the same ImageSpec always renders byte-identical output."
        ),
        # Platform is passed to `docker build --platform`, not baked into FROM:
        # BuildKit flags a constant --platform (FromPlatformFlagConstDisallowed),
        # it makes the file non-portable, and it conflicts with buildx's own
        # flag. It still feeds the digest below, so an amd64 and an arm64 build
        # remain distinct images.
        From(parent),
    ]
    if include_build_args:
        body += [Arg(name, value) for name, value in sorted(spec.build_args.items())]

    for module in modules:
        body.extend(module.instructions(context))

    module_names = tuple(m.name for m in modules)
    _check_context_files_are_used(context.files, body, f"{spec.repository}:{tier}")

    provisional = render_dockerfile(body)
    digest = content_digest(
        dockerfile=provisional,
        context_files=context.files,
        context_modes=context.modes,
        extra={
            # `parent` is in the rendered FROM already, but naming it explicitly
            # keeps the digest meaningful if the renderer ever changes.
            "parent": parent,
            "tier": tier,
            "platform": spec.target_platform,
            "build_args": dict(spec.build_args) if include_build_args else {},
            # Labels are rendered into the Dockerfile, so they are part of the
            # image and must be part of its identity.
            "labels": dict(spec.labels),
            "modules": [
                {"name": m.name, "stage": m.stage, **dict(m.identity())}
                for m in modules
            ],
        },
    )

    # Labels are appended after hashing: stamping the digest into the image must
    # not change the digest, or the value would be self-referential.
    body.append(
        Label(
            image_labels(
                tier=tier,
                digest=digest,
                modules=module_names,
                extra={**spec.labels, "dev.jormungandr.parent": parent},
            )
        )
    )

    return ComposedLayer(
        tier=tier,
        dockerfile=render_dockerfile(body),
        context_files=context.files,
        context_modes=context.modes,
        digest=digest,
        reference=image_reference(spec.repository, digest, prefix=tier),
        module_names=module_names,
        parent=parent,
    )


def compose(
    spec: ImageSpec,
    *,
    registry: ModuleRegistry | None = None,
) -> ComposedImage:
    """Resolve modules, render each tier, and derive their identities."""
    modules: tuple[Module, ...] = build_modules(
        [{"name": d.name, **d.config()} for d in spec.modules],
        registry=registry,
    )

    # resolve_order already sorted by (stage, name), so the split is a partition
    # of an ordered sequence rather than a re-sort.
    base_modules = [m for m in modules if m.stage <= spec.tier_split]
    runtime_modules = [m for m in modules if m.stage > spec.tier_split]

    base = _compose_layer(
        spec=spec,
        tier=BASE_TIER,
        parent=spec.base_image,
        modules=base_modules,
        include_build_args=True,
    )
    runtime = _compose_layer(
        spec=spec,
        tier=RUNTIME_TIER,
        parent=base.reference,
        modules=runtime_modules,
        include_build_args=True,
    )
    return ComposedImage(spec=spec, layers=(base, runtime))


def compose_workspace(
    *,
    parent: str,
    repository: str,
    clone_url: str,
    commit: str,
    platform: str,
    workdir: str,
    user: str,
    subdirectory: str | None = None,
    clone_as: str | None = None,
) -> ComposedLayer:
    """A third tier holding a repository checkout, built on the runtime image.

    This is SWE-bench's *instance* tier, and it is here for the same reason:
    the checkout is the most expensive per-task step and the one most worth
    caching. A retried run reuses the image instead of cloning again, and two
    records on the same commit share one clone.

    Cloning inside the image rather than on the host also removes the last
    thing reaching out of the container. A repository can store a symlink at
    ``subdirectory``, but inside the image it resolves against the image's own
    filesystem, so the escape that made a host-side clone dangerous cannot
    exist here.

    ``commit`` must be a resolved revision, not a branch: the digest is only
    honest if the content it names is fixed.
    """
    staging = "/tmp/jormungandr-clone"
    content = f"{staging}/{subdirectory}" if subdirectory else staging
    destination = f"{workdir}/{clone_as}" if clone_as else workdir

    body: list[Instruction] = [
        Comment(
            f"Generated by jormungandr (workspace tier). Do not edit.\n"
            f"{clone_url} @ {commit}"
            + (f", subdirectory {subdirectory}" if subdirectory else "")
        ),
        From(parent),
        # Cloning and chowning both need root; the image drops back to the
        # agent user at the end.
        User("root"),
        Run(
            [
                # git may not be in the base image, and the package manager
                # differs by distribution — the same reason useradd needs an
                # adduser fallback.
                "if ! command -v git >/dev/null 2>&1; then "
                "(apt-get update && apt-get install -y --no-install-recommends git) "
                "2>/dev/null || apk add --no-cache git; fi",
                f"git init --quiet {staging}",
                f"git -C {staging} remote add origin {clone_url}",
                # Fetch exactly one revision rather than the whole history: a
                # pinned commit is all this tier means, and --depth 1 on a
                # single sha is the cheapest way to get it.
                f"git -C {staging} fetch --quiet --depth 1 origin {commit}",
                f"git -C {staging} checkout --quiet FETCH_HEAD",
                f"mkdir -p {destination}",
                f"cp -a {content}/. {destination}/",
                f"rm -rf {staging}",
                f"chown -R {user} {workdir}",
            ]
        ),
        Workdir(workdir),
        User(user),
    ]

    digest = content_digest(
        dockerfile=render_dockerfile(body),
        extra={
            "tier": WORKSPACE_TIER,
            "parent": parent,
            "platform": platform,
            "clone_url": clone_url,
            "commit": commit,
            "subdirectory": subdirectory,
            "clone_as": clone_as,
            "workdir": workdir,
            "user": user,
        },
    )
    body.append(
        Label(
            image_labels(
                tier=WORKSPACE_TIER,
                digest=digest,
                extra={"dev.jormungandr.parent": parent},
            )
        )
    )
    return ComposedLayer(
        tier=WORKSPACE_TIER,
        dockerfile=render_dockerfile(body),
        context_files={},
        context_modes={},
        digest=digest,
        reference=image_reference(repository, digest, prefix=WORKSPACE_TIER),
        module_names=(),
        parent=parent,
    )
